### PR TITLE
Removed support for youtube_dl and added another missing protocol

### PR DESCRIPTION
**Pull request by twiclo**

### CODE REVIEW

**Comment by ticky** [comment]
I still seem to be getting a cryptic error (with `simple.rs` updated to call `yt-dlp`) even with these patches:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Json(Error("invalid type: floating point `2`, expected i64", line: 0, column: 0))', examples/simple.rs:8:10
```

even running with `RUST_BACKTRACE=full RUST_LIB_BACKTRACE=full` it doesn't point me any further than "you tried to unwrap in simple.rs", which is unhelpful - got any ideas?

**Comment by twiclo** [comment]
Are you using yt-dlp or youtube-dl? I removed support for youtube-dl

**Comment by ticky** [comment]
> (with simple.rs updated to call yt-dlp)

yt-dlp - notably your fork doesn't change the defaults to calling `yt-dlp` without setting the binary path manually

**Comment by ticky** [comment]
And I should note that this works if you roll `yt-dlp` back to 2022.11.11 but broke as of  2023.01.02.

**Comment by ticky** [comment]
Ah, the issue appears to be that `quality` is now a float on YouTube videos due to [this change](https://github.com/yt-dlp/yt-dlp/commit/9bb856998b0d5a0ad58268f0ba8d784fb9d934e3#diff-b7b9f6790de4427214b61939432e667d95b929d07fd918b9da1a36d7996cc506R3680). Going to open an issue upstream.

**Comment by ticky** [comment]
Never mind, reporting this to yt-dlp is a minefield. Opened #34 with the hopes for a quick merge.

**Comment by GyrosOfWar** [comment]
Closing this in favor of #28 (incorporated your changes into my MR)

**Pull request closed without merging**
